version: 2

models:
  - name: stg_customer
    description: Staging para tabla de clientes.
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: nation_key
        tests: [not_null]

  - name: stg_orders
    description: Staging para tabla de pedidos.
    columns:
      - name: order_key
        tests: [not_null, unique]
      - name: customer_key
        tests: [not_null]

  - name: stg_lineitem
    description: Staging para los ítems de cada pedido.
    columns:
      - name: order_key
        tests: [not_null]
      - name: line_number
        tests: [not_null]

  - name: stg_part
    description: Staging para la información de partes.
    columns:
      - name: part_key
        tests: [not_null, unique]

  - name: stg_supplier
    description: Staging para proveedores.
    columns:
      - name: supplier_key
        tests: [not_null, unique]
      - name: nation_key
        tests: [not_null]

  - name: stg_nation
    description: Staging para naciones.
    columns:
      - name: nation_key
        tests: [not_null, unique]
      - name: region_key
        tests: [not_null]

  - name: stg_region
    description: Staging para regiones.
    columns:
      - name: region_key
        tests: [not_null, unique]

  - name: stg_partsupp
    description: Staging para relación entre partes y proveedores.
    columns:
      - name: part_key
        tests: [not_null]
      - name: supplier_key
        tests: [not_null]

