models:
  - name: dim_customers
    description: Dimensión de clientes con atributos y métricas agregadas
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: number_of_orders
        description: Total de pedidos hechos por el cliente
