version: 2

sources:
  - name: TPCH_SF1  # este es el nombre que usarás luego con `source()`
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: Información de los clientes
      - name: orders
        description: Pedidos realizados por clientes
      - name: lineitem
        description: Detalle de los ítems por pedido
      - name: part
        description: Productos disponibles
      - name: supplier
        description: Proveedores de productos
      - name: nation
        description: Nacionalidades
      - name: region
        description: Regiones
