version: 2

sources:
  - name: TPCH_SF1  # este es el nombre que usarás luego con `source()`
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: Customer information including demographics and account balance.
      - name: orders
        description: Orders placed by customers
      - name: lineitem
        description: Line items for each order, including quantity and price info.
      - name: part
        description: Details about the parts that are sold.
      - name: supplier
        description: Supplier information, including nation and contact data.
      - name: nation
        description: Nations referenced by customers and suppliers.
      - name: region
        description: Regions that group nations together.
      - name: partsupp
        description: Relationship table between parts and suppliers. Each record indicates a part supplied
          by a specific supplier, along with the available quantity and supply cost.
